config {
  type: "incremental",
  schema: "citibike_stage_sql",
  name: "stg_sql_stations",
  description: "Cleaned up data for stations data source",
  columns: models.stations.columns_descriptions,
  tags: ["stage-sql"],
   bigquery: {
    partitionBy: "DATE(load_time)",
    clusterBy: ["load_id"]
  }
}


${
  dvform.get_stage_table(
    dataform.projectConfig.vars.load_id, 
    ref("src_sql_stations"), 
    models.stations.columns
  )
}
